# Generated by Django 4.1.5 on 2023-04-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0002_alter_game_managers_game_rounds_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='answer_ended',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='question_arrived',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
