# Generated by Django 4.1.5 on 2023-04-06 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia_api', '0003_round_answer_ended_round_question_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='nosy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
