# Generated by Django 4.1.5 on 2023-04-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0004_alter_round_nosy'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='qualify_ended',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
