# Generated by Django 4.1.5 on 2023-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0005_round_qualify_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='evaluated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
