# Generated by Django 4.1.5 on 2023-05-07 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0010_alter_fault_category_actionerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionerror',
            name='round',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='trivia_api.round'),
        ),
    ]
